[[redirects]]
  from = "editor/*"
  to = "editor/:splat"
  status = 200

[[redirects]]
  from = "static/*"
  to = "static/:splat"
  status = 200

[[redirects]]
  from = "*"
  to = "index.html"
  status = 200


[[headers]]
  for = "editor/static/*" 
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "static/*" 
  [headers.values]
    Cache-Control = "public, max-age=31536000"
